spring:
  datasource:
    url: jdbc:mysql://localhost:3306/course?characterEncoding=UTF8&&autoReconnect=true
    username: root
    password: 980518
    driver-class-name: com.mysql.jdbc.Driver
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
mybatis:
  mapper-locations: classpath:/mapper/**/*.xml
logging:
  level:
    com.course.server.mapper: trace