spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes[0]:
        id: system
        uri: http://127.0.0.1:9001
        predicates[0]:
          name: Path
          args[0]: /system/**
      routes[1]:
        id: business
#        uri: http://127.0.0.1:9002
        uri: lb://business
        predicates[0]:
          name: Path
          args[0]: /business/**
      routes[2]:
        id: file
#        uri: http://127.0.0.1:9002
        uri: lb://file
        predicates[0]:
          name: Path
          args[0]: /file/**
server:
  port: 9000
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
